version: '3'

services:
  db:
    container_name: store_db
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    volumes:
      - ../db_data:/var/lib/mysql
  web:
    container_name: store_web
    image: nginx:mainline-alpine
    depends_on:
      - php
    volumes:
        - ../src:/var/www/html
        - ./config/site.conf:/etc/nginx/conf.d/default.conf
        - ./log/access.log:/var/log/access.log
        - ./log/error.log:/var/log/error.log
    env_file:
      - .env
    ports:
        - 80:80
  php:
    container_name: store_php
    build: .
    depends_on:
      - db
    volumes:
        - ../src:/var/www/html
  phpmyadmin:
    container_name: store_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
  redis:
    container_name: store_redis
    image: redis:alpine
    restart: always