version: '3'

services:
  db:
    container_name: store_db
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    volumes:
      - ../db_data:/var/lib/mysql
  web:
    container_name: store_web
    image: rossbrandon/magento-store:jessie-php5.6-apache
    restart: always
    depends_on:
      - db
      - redis
      - mail
    volumes:
      - ../code/backend:/var/www/html
      - ./etc/modules/Cm_RedisSession.xml:/var/www/html/app/etc/modules/Cm_RedisSession.xml
      - ./etc/local.xml:/var/www/html/app/etc/local.xml
      - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./etc/apache2.conf:/etc/apache2/apache2.conf
      - ./log/56_error.log:/var/www/56_error.log
      - ./log/56_access.log:/var/www/56_access.log
    env_file:
      - .env
    ports:
      - 80:80
  phpmyadmin:
    container_name: store_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
  redis:
    container_name: store_redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  mail:
    container_name: store_mail
    image: djfarrelly/maildev
    ports:
      - 8081:80