version: '3'

services:
  db:
    container_name: store_db
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    volumes:
      - ../db_data:/var/lib/mysql
  web:
    container_name: store_web
    image: rossbrandon/magento-store
    restart: always
    depends_on:
      - db
    volumes:
      - ../src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/virtualhost-php56.conf:/etc/apache2/sites-available/001-virtualhost-php56.conf
      - ./logs/56_error.log:/var/www/56_error.log
      - ./logs/56_access.log:/var/www/56_access.log
    env_file:
      - .env
    ports:
      - 80:80
  phpmyadmin:
    container_name: store_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
  redis:
    container_name: store_redis
    image: redis:alpine
    restart: always